spring:
  mail:
    host: smtp.gmail.com
    username: kumaunretailstore@gmail.com
    password: nikrvpkkgyrvedcf
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true


#web:
#  cors:
#    allowed-origins: "http://localhost:3000"
#    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
#    max-age: 3600
#    allowed-headers: "Requestor-Type"
#    exposed-headers: "X-Get-Header"
